FROM node:16-alpine

WORKDIR /opt/app

COPY ./server/package*.json ./server/
COPY ./shared ./shared

WORKDIR /opt/app/server

RUN npm install;

COPY ./server ./

RUN npm run build


EXPOSE 8000

CMD [ "node", "dist/index.js" ]
